spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    username: 'postgres'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/hibernatedb
