spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    username: 'postgres'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/hibernatedb

logging:
  level:
    org.apache.util.net: WARN
    todolist.SpringApp: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG