spring:
  mail:
    host: smtp.mail.ru
    port: 465
    username: thunderbass@mail.ru
    password: WJcrSYqeHyTs4Rj80uKe
    properties:
      mail:
        smtp:
          auth: true
#          starttls.enable: true
          transport.protocol: smtp
          socketFactory.port: 465
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          socketFactory.fallback: false
          ssl.enable: true
        debug: true
  rabbitmq:
    host: rabbit
    port: 5672

server:
  port: 8081

logging:
  level:
    org.springframework.mail: debug
    org.springframework.amqp: debug
