spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: 'postgres'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/hibernatedb
  mvc:
    log-request-details: true

logging:
  level:
    org.apache.util.net: WARN
#    todolist.SpringApp: TRACE
#    todolist.TodoController: TRACE
    todolist: debug
#    org.springframework.web.servlet.DispatcherServlet: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG
    org.liquibase: debug

# vars
jwt.secret: asdfgh
jwt.expireMinutes: 600

lib.email.url: 'http://localhost:8081/email'
lib.email.message-service: email   # email or rabbit